### PR TITLE
The First Great Authentication Refactor

### PR DESCRIPTION
**Pull request by tecywiz121**
# Summary
Lots of changes going in here. I probably could have, and should have, broken this up into smaller pull requests, but faster forward!

# Highlights
 - Implement `FromRequest` for `User` so that it can be used directly in route function arguments.
 - Create a new trait `Auth` which is like `Hook`, but for authentication.
 - Create `bellhop-auth-header` which, unsurprisingly, gets the email address from a header (inc.)
 - Rework how the database type is hidden from hooks and auth modules.
 - Put the email-only authentication into `bellhop-auth-dummy` (inc.)

### CODE REVIEW

**Comment by tdickers** [comment]
I think it's time we discussed code commenting, both for the sake of potential consumer/contributors and our own when coming in cold.

Would you be terribly bothered if I asked you to start adding doc comments?

**Comment by tecywiz121** [comment]
> Hmm, I wonder if we need an optional feature to convert username-based headers to emails. e.g. If some forwarding proxy hooked into LDAP only returns username, but we're storing the email `username@co.example`. The real solution there would be to separate emails and usernames, though.

I think `mail` is a fairly common attribute for LDAP. Our server provides it at least. Maybe down the road we can do something more in-depth than a regex on the header.

> I think it's time we discussed code commenting, both for the sake of potential consumer/contributors and our own when coming in cold.

I have #16 open to make doc comments mandatory. Besides that, are there other kinds of comments you'd like to see?

**Comment by tdickers** [comment]
Not off the top of my head.

**Comment by tdickers** [comment]
Do you intend to add comments to this PR?

**Comment by tecywiz121** [comment]
I've got 3 or 4 more pull requests lined up after this one. I'll do a sweep after if that's okay by you.

**Comment by tdickers** [comment]
Sure is.

**Pull request merged**
